<?php

// PLEASE DO NOT EDIT THIS FILE!
// INSTEAD, COPY IT TO config.local.php AND THEN EDIT IT

// Add directories which need mysql_* methods (plugin 001)
// Add '!' in front of a dir to exclude the directory instead of including it
$xxx_vts_prepend_config['directories_need_mysql'] = array(
	'/'
);

// Add directories which need register globals (plugin 002)
// Add '!' in front of a dir to exclude the directory instead of including it
$xxx_vts_prepend_config['directories_need_registerglobals'] = array(
#	'/home/user1/',
#	'!/home/user1/secure/',
#	'/home/user2/'
);

// Add directories which need ereg_* methods (plugin 003)
// Add '!' in front of a dir to exclude the directory instead of including it
$xxx_vts_prepend_config['directories_need_ereg'] = array(
#	'/home/user1/',
#	'!/home/user1/secure/',
#	'/home/user2/'
);

// Add directories which are protected with a (weak) XSS WAF (plugin 004)
// Add '!' in front of a dir to exclude the directory instead of including it
$xxx_vts_prepend_config['directories_need_anti_xss'] = array(
#	'/home/user1/',
#	'!/home/user1/secure/',
#	'/home/user2/'
);
